### ISSUE TITLE
mina executable conflicts with executable from ruby gem

### ISSUE THREAD

**Issue by Asp1d** [CenturyUna/mina#19]
Maybe you should call cli tool `minajs` or something?

**Comment by stAndrei** [comment]
I have the same problem.

**Comment by fanweixiao** [comment]
I've considered about `minajs` renaming, but the ruby mina project seems non-active in the past 2 years. and, we use the same configuration file structure and improved by add new options to config. I hope ppl using the ruby one can change to this one :smile:

**Comment by rapind** [comment]
Unfortunately mina ruby users can't simply switch due to library integrations like rvm / rbenv mina etc. Plus you're making an assumption that one would want to use a node library for ruby deployments. Please reconsider.
