### ISSUE TITLE
Error in Gitbash

### ISSUE THREAD

**Issue by hassansin** [CenturyUna/mina#22]
I am trying to use this in Gitbash. My config: 
```
{
  ...
  "server_dir": "/var/www/deploy",
  "repo": "git@bitbucket.org:user/repo.git",
  "prj_git_relative_dir": "",
  "branch": "master",
  "force_regenerate_git_dir": false,
  ....
}
```

But I'm getting this error `no such file or directory`. Here is the log. Note that the path separator is changed:

> Using config file 'deploy.json'
----> root@domain.com Create subdirs
----> mkdir -p \var\www\deploy\shared
----> ok
----> mkdir -p \var\www\deploy\releases
----> ok
----> mkdir -p \var\www\deploy\tmp
----> ok
----> root@domain.com Create shared dirs
----> mkdir -p \var\www\deploy\shared\node_modules
----> ok
----> mkdir -p \var\www\deploy\shared\db
----> ok
----> cd \var\www\deploy
----> Command failed with code 1
----> rm -rf \var\www\deploy\releases$rno
----> ok
bash: line 56: cd: \var\www\deploy: No such file or directory

I also don't see any shared, releases or tmp folders created in the server. Any idea?

**Comment by fanweixiao** [comment]
the directory is weird, it should be `mkdir -p /var/www/deploy/shared` instead of `mkdir -p \var\www\deploy\shared`. If you run `mkdir -p \var\www\deploy\shared`, you will get a directory named `varwwwdeployshared`.

What's the OS of your client and server?

**Comment by hassansin** [comment]
Client is Windows 7, using GitBash
Server is Ubuntu 14.04

Checked the server to see if there is any varwwwdeployshared directory:
```
cd ~
ls -l
drwxr-xr-x   2 root root  4096 Mar 20 00:27 \var\www\deploy\releases/
drwxr-xr-x   2 root root  4096 Mar 20 00:27 \var\www\deploy\shared/
drwxr-xr-x   2 root root  4096 Mar 20 00:27 \var\www\deploy\shared\db/
drwxr-xr-x   2 root root  4096 Mar 20 00:27 \var\www\deploy\shared\node_modules/
drwxr-xr-x   2 root root  4096 Mar 20 00:27 \var\www\deploy\tmp/
```

looks like the folders are created in HOMEDIR instead. Probably it's getting the path separator from the client os?

**Comment by hassansin** [comment]
Maybe it's `path.join` used in BashScript.cd and BashScript.mkdir. Any workaround for it? Thanks

**Comment by fanweixiao** [comment]
Oh ... I don't have any experiences on GitBash/Windows SSH Client, I'll keep this issue open. Would you like edit the title of this issue to make a clearer information, maybe someone can help later :smiley_cat:

**Comment by hassansin** [comment]
replacing `return this.cmd("mkdir", "-p", path.join.apply(path, dir_components))` with
 `return  this.cmd("mkdir", "-p", dir_components.join('/'))` fixed the problem. I think it's fine if we just join the directory components with '/', since bash treats multiple path separator as one. I can send a pull request if you agree with the fix.

**Comment by fanweixiao** [comment]
I think if we use the OS detecting way seems better
